version: '3.8'

services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - express-app
